os: linux
dist: focal

install: skip

jobs:
  include:
    - language: shell
      script: sleep 10
    - language: nodejs
      node_js: lts/*
      script: sleep 15
    - language: ruby
      ruby: 3.1.2
      script: sleep 10
    - language: python
      python: 3.12
      script: sleep 10
    - language: python
      python: 3.11
      script: sleep 10
    - language: shell
      script: sleep 20
    - language: nodejs
      node_js: lts/*
      script: sleep 25
    - language: ruby
      ruby: 3.1.2
      script: sleep 30
    - language: python
      python: 3.12
      script: sleep 40
    - language: python
      python: 3.11
      script: sleep 60
