os: linux
dist: focal
jobs:
  include:
    - name: "Job to crate custom image my_custom_name_20260129_0003"
      vm:
        create:
          name: my_custom_name_20260129_0003
      script: echo "Job one..."
